dist: xenial
sudo: true
language: python
python:
  - "3.8"
matrix:
  include:
    - python: 3.8
cache: pip
install:
  - pip install -r requirements.txt
  - pip install -U pytest pytest-cov pytest-doctestplus codecov
  - pip install black
script:
  - pytest --cov=brainlit tests/
  - black --check --diff ./brainlit ./tests
after_success:
  - codecov

deploy:
  - provider: pypi
    user: "__token__"
    password:
      secure: $PYPI
    skip_existing: true
    on:
      branch: master
      tags: true
      repo: neurodata/brainlit
      python: "3.8"
